#Two Factor Anova /Ancova
getwd()
Adv.DataFrame=read.csv("paul-newfood.csv", header = TRUE)
View(Adv.DataFrame)
attach(Adv.DataFrame)
pricefactor=factor(PriceLevel,c(1,2,3),labels = c("Low","Medium","High"))
adfactor=factor(AdLevel,c(1,2),labels = c("Low","High"))
anova_foodadv=aov(Sales~pricefactor+adfactor)
summary(anova_foodadv)
print(summary(anova_foodadv),digits=10)
interaction.plot(pricefactor,adfactor,Sales,col = c("RED","GREEN"),main="Interaction plot")
anova_foodadv1=aov(Sales~pricefactor+adfactor+pricefactor*adfactor)
print(summary(anova_foodadv1),digits = 10)
#summary(anova_foodadv1)
cor(Sales,StoreSize)
cor.test(Sales,StoreSize)
anova_foodadv3=aov(Sales~StoreSize+pricefactor+adfactor+pricefactor*adfactor)
print(summary(anova_foodadv3),digits = 10)
